apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-mlflow
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlflow-operator-mlflow-integration
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-runner-mlflow
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlflow-operator-mlflow-integration
subjects:
  - kind: ServiceAccount
    name: pipeline-runner-dspa
    namespace: ${NAMESPACE}
