apiVersion: v1
kind: Secret
metadata:
  name: ${DOMAIN_NAME}-pipeline-s3
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<your-s3-access-key>"
  AWS_SECRET_ACCESS_KEY: "<your-s3-secret-key>"
