model:
  provider: custom
  model: qwen36-27b
  base_url: http://maas.apps.ocp.cloud.rhai-tmm.dev/prelude-maas/qwen36-27b/v1
  api_key: "${OPENAI_API_KEY}"
mcp_servers: {}
dashboard:
  oauth:
    client_id: hermes-dashboard
    portal_url: https://keycloak-keycloak.apps.sno.sandbox1254.opentlc.com/realms/prelude-m6wl4-g29zx
  public_url: https://retail-hermes.apps.prelude-m6wl4-vs9lb.sandbox1832.opentlc.com
