---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: finance-dept
  labels:
    acme-retail.example.com/department: finance
users:
  - fred
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: sales-dept
  labels:
    acme-retail.example.com/department: sales
users:
  - sally
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: ops-dept
  labels:
    acme-retail.example.com/department: ops
users:
  - alex
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: retail-admins
  labels:
    acme-retail.example.com/role: admin
users:
  - prelude
