apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ${DOMAIN_NAME}-mcp-server
  namespace: ${NAMESPACE}
  labels:
    app: ${DOMAIN_NAME}-mcp-server
spec:
  lookupPolicy:
    local: true
