version: 1

filesystem_policy:
  include_workdir: true
  read_only: [/usr, /lib, /proc, /dev/urandom, /opt, /etc, /var/log]
  read_write: [/sandbox, /tmp, /dev/null, /dev/pts]
landlock:
  compatibility: best_effort
process:
  run_as_user: sandbox
  run_as_group: sandbox

network_policies:
  mcp:
    name: mcp-servers
    endpoints:
      - host: retail-finance-mcp.openshell.svc.cluster.local
        port: 9090
      - host: retail-sales-mcp.openshell.svc.cluster.local
        port: 9090
      - host: retail-ops-mcp.openshell.svc.cluster.local
        port: 9090
    binaries:
      - path: /opt/hermes/.venv/bin/python*
      - path: /usr/bin/python*
      - path: /usr/bin/curl
  inference:
    name: maas-inference
    endpoints:
      - host: maas.apps.ocp.cloud.rhai-tmm.dev
        port: 443
      - host: maas.apps.ocp.cloud.rhai-tmm.dev
        port: 80
    binaries:
      - path: /opt/hermes/.venv/bin/python*
      - path: /usr/bin/python*
      - path: /usr/bin/curl
  npm:
    name: npm-registry
    endpoints:
      - host: registry.npmjs.org
        port: 443
    binaries:
      - path: /usr/local/bin/node
      - path: /usr/local/bin/npm
  pypi:
    name: pypi-packages
    endpoints:
      - host: pypi.org
        port: 443
      - host: files.pythonhosted.org
        port: 443
    binaries:
      - path: /usr/local/bin/uv
      - path: /opt/hermes/.venv/bin/uv
      - path: /opt/hermes/.venv/bin/pip
      - path: /opt/hermes/.venv/bin/python*
      - path: /usr/bin/python*
  model-catalog:
    name: model-catalog
    endpoints:
      - host: models.dev
        port: 443
    binaries:
      - path: /opt/hermes/.venv/bin/python*
      - path: /usr/bin/python*
  dashboard:
    name: hermes-dashboard-internal
    endpoints:
      - host: 127.0.0.1
        port: 9119
      - host: 127.0.0.1
        port: 18642
      - host: 127.0.0.1
        port: 8889
    binaries:
      - path: /usr/local/bin/node
      - path: /opt/hermes/.venv/bin/python*
      - path: /usr/bin/python*
  keycloak:
    name: keycloak-oauth
    endpoints:
      - host: keycloak-keycloak.apps.sno.sandbox1254.opentlc.com
        port: 443
    binaries:
      - path: /opt/hermes/.venv/bin/python*
      - path: /usr/bin/python*
      - path: /usr/local/bin/node
